version: '3.8'

services:

  django:
    container_name: inventory-py-django
    build:
      context: .
    command: gunicorn itdept.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    image: inventory-py-django
    environment:
      - DEBUG=1

