# Generated by Django 4.2 on 2023-05-17 03:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_order_device_year_ordernotes_orderitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitems',
            options={'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='ordernotes',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Order Notes'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('DEPLOYED', 'Deployed'), ('RECEIVED', 'Received'), ('RETURNED', 'Returned')], default='DRAFT', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordernotes',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
